### PR TITLE
GMM Plugin

### PR DESCRIPTION
**Pull request by jkarnows**
There exist multiple initialization methods, including using K-means. The code does not crash the program.

The major issue for this plugin is that there are singularities in GMM causing infinite log likelihood. I altered the code so that if a user runs GMM on the data and there was not a successful run, all labels are set to zero. Otherwise, it will return the run that worked. There exist some methods to correct for the bad covariance matrices, but I do not have time to implement them.

I also tried out this method with higher dimensional data. There could probably be some good improvements for GMM to work on this higher dimensional data, but now it takes a really long time to compute. I wrote this code before I learned some better practice for more efficient algorithms. I think there could be some work done to improve the space and time of this implementation. It doesn't crash the machine, though. And it works really really quickly for low dimensional data.

### CODE REVIEW

**Comment by jkarnows** [comment]
It's slower on larger datasets because it implements the full covariance version of GMM and does not have an option for spherical, tied, or diagonal versions.

**Comment by lvdmaaten** [comment]
I think a standard way to deal with the singularity-problems you describe is to simply remove the Gaussian from the mixture when such a singularity occurs. (The singularity is the result of the Gaussian modeling just a single point, as a result of which the covariance goes to zero and becomes non-invertible. Since it is only modeling a single data point, it does not hurt much in terms of log-likelihood to remove such a Gaussian.)

**Comment by jkarnows** [comment]
Yeah, that was one of the main methods I saw for fixing this. I think it's a good idea but I didn't get a chance to look at my old code to implement that change. I'm moving and won't have access to a Mac to work through the changes but it's good to note that alteration here.

**Comment by jmlewis** [comment]
Thanks Jeremy!

**Pull request merged**
